# Wowchemy Website Builder
# https://wowchemy.com
#
# The presence of this file is for compatibility with Blogdown and Forestry.
# If you are not using those tools, this file may be deleted.
#
# The actual configuration files are stored in the `config/_default/` folder.

#baseURL = 'https://acmrecsys.github.io/rsss2024/'
#languageCode = 'en-us'
#title = 'ACM Europe School on Recommender Systems 2024'
#theme = 'Academic'